# Standards: 0.11
---

- include_tasks: preflight.yml
  when: cis_apply_level_1_profile or cis_apply_level_2_profile

- include_tasks: "level-1.yml"
# become: yes
  when: cis_apply_level_1_profile

- include_tasks: "level-2.yml"
# become: yes
  when: cis_apply_level_2_profile

- include_tasks: ipv6.yml
# become: yes

- include_tasks: ntp_pool.yml

- name: flush handlers
  meta: flush_handlers
