# Standards: 0.11
---

# Preflight checks
- name: ansible_distribution
  debug:
    var: ansible_distribution

- name: ansible_distribution_version
  debug:
    var: ansible_distribution_version

- name: Preflight - Fail if host is not suitable for this benchmark
  fail:
    msg: "This benchmark is not suitable for the destination operating system"
  when: (ansible_distribution is not defined) or (ansible_distribution_version is not defined) or (ansible_distribution_version not in cis_target_os_versions) or (ansible_distribution != cis_target_os_distribution)
  tags: always

- name: List Level-1 exclusions
  debug:
    var: cis_level_1_exclusions

- name: List Level-2 exclusions
  debug:
    var: cis_level_2_exclusions
