# Standards: 0.11
---

# 3.6 Disable IPv6 (Not Scored)

- name: 3.6 - Check for existence of module configuration
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_3_6
  tags:
    - level-2
    - section-3
    - "3.6"
    - scored

- name: 3.6 - Disable IPv6 kernel module
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "options ipv6 disable=1\n"
  when: modprobe_3_6.stat.exists is not defined or not modprobe_3_6.stat.exists
  tags:
    - level-2
    - section-3
    - "3.6"
    - scored

- name: 3.6 - Disable IPv6 kernel module
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^options ipv6 disable="
    line: "options ipv6 disable=1"
  when: modprobe_3_6.stat.exists is defined and modprobe_3_6.stat.exists
  tags:
    - level-2
    - section-3
    - "3.6"
    - scored

- name: 3.6 - Check for existence of bootloader configuration
  stat:
    path: "{{ cis_grub_configuration_filename }}"
  register: bootloader_config_3_6
  tags:
    - level-2
    - section-3
    - "3.6"
    - scored

- name: 3.6 - Disable IPv6 (bootloader)
  replace:
    dest: "{{ cis_grub_configuration_filename }}"
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=.*)\"$'
    replace: '\1 ipv6.disable=1"'
  when: bootloader_config_3_6.stat.exists and in_container is not defined
  notify: Reconfigure GRUB
  tags:
    - level-2
    - section-3
    - "3.6"
    - scored
