---

# 4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)

- name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  replace:
    dest: "{{ cis_grub_configuration_filename }}"
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=.*)\"$'
    replace: '\1 audit=1"'
  notify: Reconfigure GRUB
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored
