# Standards: 0.11
---

# 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected(Scored)

- name: 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected(Scored)
  shell: "grep MAC-policy {{ cis_audit_rules_filename }}"
  register: MAC-policy
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.7"
    - level-2
    - section-4
    - scored


- name: 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected(Scored)(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.7 Ensure events that modify date and time information are collected'
    - '-w /etc/selinux/ -p wa -k MAC-policy'
  when:
    ("'-w /etc/selinux/ -p wa -k MAC-policy' not in MAC-policy.stdout")
  tags:
    - "4.1.7"
    - level-2
    - section-4
    - scored
