---
# Standards: 0.11

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled

- name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: "install cramfs /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Remove cramfs module"
        modprobe:
            name: cramfs
            state: absent
  when:
      - amazon2cis_rule_1_1_1_1
      - ansible_connection != 'docker'
  tags:
      - level1
      - automated
      - patch
      - rule_1.1.1.1
      - cramfs
      - modprobe

