# Standards: 0.11
---

# 1.1.6 Ensure separate partition exists for /var (Scored)

- name: 1.1.6 - Ensure separate partition exists for /var (Scored)
  mount:
    name: "{{ item.mount }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
    opts: "{{item.options}}"
  when: item.mount == '/var'
  with_items: "{{ ansible_mounts }}"
  tags:
      - level-1
      - section-1
      - "1.1.6"
      - scored
