# 1.1.1.2 - Ensure mounting of hfs filesystems is disabled

- name: "1.1.1.2 | PATCH | Ensure mounting of hfs filesystems is disabled"
  block:
      - name: "1.1.1.2 | PATCH | Ensure mounting of hfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install hfs(\\s|$)"
            line: "install hfs /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.2 | PATCH | Ensure mounting of hfs filesystems is disabled | hfs module"
        modprobe:
            name: hfs
            state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.2"
    - scored

