# 1.1.1.3 - Ensure mounting of hfsplus filesystems is disabled

- name: "1.1.1.2 | PATCH | Ensure mounting of hfsplus filesystems is disabled"
  block:
      - name: "1.1.1.2 | PATCH | Ensure mounting of hfsplus filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install hfsplus(\\s|$)"
            line: "install hfsplus /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.2 | PATCH | Ensure mounting of hfsplus filesystems is disabled | Remove hfsplus module"
        modprobe:
            name: hfsplus
            state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.3"
    - scored
