# 1.1.1.4 - Ensure mounting of squashfs filesystems is disabled

- name: "1.1.1.4 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  block:
      - name: "1.1.1.4 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install squashfs(\\s|$)"
            line: "install squashfs /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.4 | PATCH | Ensure mounting of cramfs filesystems is disabled | Remove squashfs module"
        modprobe:
            name: squashfs
            state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored
