# 1.1.1.5 - Ensure mounting of udf filesystems is disabled

- name: "1.1.1.5 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
      - name: "1.1.1.5 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: "install udf /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.5 | PATCH | Ensure mounting of udf filesystems is disabled | Remove udf module"
        modprobe:
            name: udf
            state: absent
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

