# Standards: 0.11
---

# 1.6.1.2. Ensure the SELinux state is enforcing (Scored)

- name: 1.6.1.2 Ensure the SELinux state is enforcing (Scored)
  selinux:
    policy: targeted
    state: enforcing
  when: cis_disable_selinux|bool == false
  tags:
      - level-1
      - section-1
      - "1.6.1.2"
      - scored

- name: 1.6.1.2 Ensure the SELinux state is permissive (Scored)
  selinux:
    policy: targeted
    state: permissive
  when: cis_disable_selinux|bool == true
  tags:
      - level-1
      - section-1
      - "1.6.1.2"
      - scored