# Standards: 0.11
---

# 1.6.1.2. Ensure the SELinux state is enforcing (Scored)
- name: Install the SE Linux requirements - libselinux-python
  command: yum install libselinux-python -y

- name: Install the SE Linux requirements - policycoreutils-python
  command: yum install policycoreutils-python -y

- name: pip3 install selinux
  command: pip3 install selinux

- name: Ensure SELinux is not disabled
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: '^SELINUX=enforcing'
  when: cis_disable_selinux|bool == false
  tags:
    - level-1
    - section-1
    - "1.6.1.2"
    - scored

- name: Ensure SELinux policy is targeted
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUXTYPE=.*'
    replace: '^SELINUXTYPE=targeted'
  when: cis_disable_selinux|bool == true
  tags:
    - level-1
    - section-1
    - "1.6.1.2"
    - scored
