# Standards: 0.11
---

# 1.6.1.3 Ensure SELinux policy is configured (Scored)

- name: 1.6.1.3 Ensure SELinux policy is configured (Scored)
  selinux:
    policy: targeted
    state: enforcing
  when: cis_disable_selinux|bool == false
  tags:
      - level-1
      - section-1
      - "1.6.1.3"
      - scored

- name: 1.6.1.3 Ensure SELinux policy is configured (Scored)
  selinux:
    state: disabled
  when: cis_disable_selinux|bool == true
  tags:
      - level-1
      - section-1
      - "1.6.1.3"
      - scored