# Standards: 0.11
---

# 1.8 Ensure updates, patches, and additional security software are installed

- name: 1.8 - Ensure updates, patches, and additional security software are installed
  yum:
    name: "*"
    state: latest
  tags:
    - level-1
    - "1.8"
    - not-scored
  when:
    - full_upgrade
