# Standards: 0.11
---

# 2.1.6 Ensure rsh server is not enabled

- name: 2.1.6 - Ensure rsh server is not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - rexec
    - rlogin
    - rsh
  ignore_errors: true
  tags:
    - level-1
    - section-2
    - "2.1.6"
    - scored
