# Standards: 0.11
---

# 2.1.1.1 Ensure time synchronisation is in use

- name: 2.1.1.1 - Ensure ntp is installed if applicable
  shell: "yum {{ item.state }} {{ item.name }} -y"
  when: cis_enable_ntp and not cis_enable_chrony
  with_items:
    - { name: "ntp", state: "install" }
    - { name: "chrony", state: "remove" }
  tags:
    - level-1
    - section-4
    - "2.1.1.1"
    - not-scored

- name: 2.1.1.1 - Ensure chrony is installed if applicable
  shell: "yum {{ item.state }} {{ item.name }} -y"
  when: cis_enable_chrony and not cis_enable_ntp
  with_items:
    - { name: "ntp", state: "remove" }
    - { name: "chrony", state: "install" }
  tags:
    - level-1
    - section-4
    - "2.1.1.1"
    - not-scored
