# Standards: 0.11
---

# 2.2.10 Ensure HTTP server is not enabled

- name: 2.2.10 - Ensure HTTP server is not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - httpd
    - apache
    - apache2
    - nginx
    - lighttpd
  ignore_errors: true
  tags:
    - level-1
    - "2.2.10"
    - scored
