# Standards: 0.11
---

# 2.2.1.2 Ensure ntp is configured
- name: Check existing ntp -u options
  command: grep -q '\-u ntp:ntp' /etc/init.d/ntpd
  register: checkntpconf
  check_mode: false
  ignore_errors: true
  changed_when: false
  tags:
    - level-1
    - "2.2.1.2"
    - scored

- name: Set Options -u ntp:ntp in /etc/sysconfig/ntpd
  replace:
    path: /etc/sysconfig/ntpd
    regexp: '^OPTIONS=.*$'
    replace: 'OPTIONS="-u ntp:ntp"'
  when: checkntpconf.rc != 0
  tags:
    - level-1
    - "2.2.1.2"
    - scored

- name: Set Restrict -6
  lineinfile:
    path: /etc/ntp.conf
    insertbefore: 'restrict default nomodify notrap nopeer noquery'
    line: 'restrict -6 default kod nomodify notrap nopeer noquery'
  tags:
    - level-1
    - "2.2.1.2"
    - scored

- name: Set Restrict -4
  lineinfile:
    path: /etc/ntp.conf
    insertbefore: 'restrict -6 default kod nomodify notrap nopeer noquery'
    line: 'restrict -4 default kod nomodify notrap nopeer noquery'
  tags:
    - level-1
    - "2.2.1.2"
    - scored
