# Standards: 0.11
---

# 2.2.1 Ensure NIS Client is not installed

- name: 2.2.1 - Ensure NIS Client is not installed
  shell: "yum remove ypbind -y"
  tags:
    - level-1
    - section-2
    - "2.2.1"
    - scored
