# Standards: 0.11
---

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IPv4 forwarding is disabled
  sysctl:
    name: net.ipv4.ip_forward
    value: "1" ## Enabled based as it breaks EKS cluster DNS
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IPv6 forwarding is disabled
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1" ## Enabled based as it breaks EKS Cluster DNS for ipv6
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored
  ignore_errors: yes

- name: 3.1.1 - Ensure IPv6 router advertisement is accepted on specific interface
  sysctl:
    name: net.ipv6.conf.eth0.accept_ra
    value: "2" ## Ensure ra is accepted on interface eth0 even if ip forwarding is enabled
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.1"
  ignore_errors: yes
  
- name: 3.1.1 - Ensure IP forwarding is disabled in active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.ip_forward=1"  ## Enabled based as it breaks EKS cluster DNS
    - "sysctl -w net.ipv4.route.flush=1"
    - "sysctl -w net.ipv6.conf.all.forwarding=1"  ## Enabled based as it breaks EKS Cluster DNS for ipv6
    - "sysctl -w net.ipv6.conf.eth0.accept_ra=2  ## ra must be enabled specifically on eth0 in order to get default ipv6 route
    - "sysctl -w net.ipv6.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored
  ignore_errors: yes

