# Standards: 0.11
---

# 3.3.1 Ensure TCP Wrappers is installed

- name: 3.3.1 - Ensure TCP Wrappers is installed
  shell: "yum install tcp_wrappers -y"
  tags:
    - level-1
    - section-3
    - "3.3.1"
    - scored
