# Standards: 0.11
---

# 3.4.1 Ensure TCP Wrappers is installed

- name: 3.4.1 - Ensure TCP Wrappers is installed
  yum:
    name: "tcp_wrappers"
    state: latest
  tags:
    - level-1
    - section-3
    - "3.4.1"
    - scored
