# Standards: 0.11
---

# 3.5.3 Ensure iptables is installed

- name: 3.5.3 - Ensure iptables is installed
  shell: "yum install iptables -y"
  tags:
    - level-1
    - section-3
    - "3.5.3"
    - scored
