# Standards: 0.11
---

# 3.6.5 Ensure firewall rules exist for all open ports

- name: 3.6.5 - Ensure firewall rules exist for all open ports
  debug:
    msg: "WARNING - We are already checking this as part of security groups."
  tags:
    - level-1
    - section-3
    - "3.6.5"
    - not-scored
    

- name: 3.6.5 - Ensure firewall rules exist for accepting SSH connections
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  become: yes
  tags:
    - level-1
    - section-3
    - "3.6.5"
    - not-scored
