# Standards: 0.11
---

# 4.2.3 Ensure rsyslog or syslog-ng is installed

- name: 4.2.3 - Ensure rsyslog is installed
  shell: "yum {{ item.state }} {{ item.name }} -y"
  when: cis_enable_rsyslog and not cis_enable_syslog_ng
  with_items:
    - { name: "rsyslog", state: "install" }
    - { name: "syslog-ng", state: "remove" }
  tags:
    - level-1
    - section-4
    - "4.2.3"
    - scored

- name: 4.2.3 - Ensure syslog-ng is installed
  shell: "yum {{ item.state }} {{ item.name }} -y"
  when: cis_enable_syslog_ng and not cis_enable_rsyslog
  with_items:
    - { name: "rsyslog", state: "remove" }
    - { name: "syslog-ng", state: "install" }
  tags:
    - level-1
    - section-4
    - "4.2.3"
    - scored
