# Standards: 0.11
---

# 5.3.4 Ensure password hashing algorithm is SHA-512
- name: 5.3.4 - Ensure password hashing algorithm is SHA-512 (/etc/pam.d/system-auth)
  pamd:
    name: system-auth
    type: password
    control: sufficient
    module_path: pam_unix.so
    new_control: sufficient
    module_arguments: sha512
    state: updated
  tags:
    - level-1
    - section-5
    - "5.3.4"
    - scored

- name: 5.3.4 - Ensure password hashing algorithm is SHA-512 (/etc/pam.d/password-auth)
  pamd:
    name: password-auth
    type: password
    control: sufficient
    module_path: pam_unix.so
    new_control: sufficient
    module_arguments: sha512
    state: updated
  tags:
    - level-1
    - section-5
    - "5.3.4"
    - scored
