# Standards: 0.11
---

# 5.3.4 Ensure password hashing algorithm is SHA-512

- name: 5.3.4 - Ensure password hashing algorithm is SHA-512
  command: "authconfig --update --passalgo=sha512"
  tags:
    - level-1
    - section-5
    - "5.3.4"
    - scored
