# Standards: 0.11
---

# 6.1.1 Audit system file permissions (Not Scored)

- name: 6.1.1 Audit system file permissions (Not Scored)
  shell: rpm -Va --nomtime --nosize --nomd5 --nolinkto > /tmp/test.out 2>&1
  args:
    creates: /tmp/test.out
  tags:
    - level-1
    - section-6
    - "6.1.1"
    - not-scored
